version: '3.8'
services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ../backend/.env
    ports:
      - 8017:8017
    expose:
      - 8017

  nginx:
    image: nginx:1.28.0-alpine
    ports:
      - 80:80
      - 443:443 
    volumes:
      - ../frontend/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro